services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: clientesdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  kafka:
    image: bitnami/kafka:3.6
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"

  clientes-service:
    build: .
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/clientesdb
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      SPRING_FLYWAY_URL: jdbc:mysql://mysql:3306/clientesdb
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: root

      APP_JWT_SECRET: "super-secret-demo-change-me"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
