server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ApplicantManagmentSystem

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

  jackson:
    deserialization:
      fail-on-unknown-properties: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      probes:
        enabled: true

app:
  security:
    allowed-email-domain: ${ALLOWED_EMAIL_DOMAIN:seek.com}
    jwt:
      secret: ${JWT_SECRET}
      issuer: ${JWT_ISSUER:clients-service}
      ttl-minutes: ${JWT_TTL_MINUTES:60}

  life:
    expectancy-years: ${LIFE_EXPECTANCY_YEARS:73}

openapi:
  title: Applicant Management System API
  description: API para gesti√≥n de clientes
  version: v1
  terms-of-service: https://example.com/terms
  contact:
    name: DevPull
    url: https://www.devpull.dev
    email: hello@devpull.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  ui:
    enabled: ${OPENAPI_UI_ENABLED:true}
    path: ${OPENAPI_UI_PATH:/swagger}

springdoc:
  swagger-ui:
    path: ${OPENAPI_UI_PATH:/swagger}
  api-docs:
    path: /v3/api-docs
