spring:
  flyway:
    enabled: false

logging:
  level:
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.asyncer.r2dbc.mysql: DEBUG
    io.r2dbc.mysql: DEBUG

management:
  endpoint:
    health:
      show-details: always

