server:
  port: 8080

spring:
  application:
    name: ApplicantManagmentSystem

  r2dbc:
    url: r2dbc:mysql://localhost:3306/clientsdb
    username: root
    password: admin123

  #  flyway:
  #    url: jdbc:mysql://localhost:3306/clientsdb
  #    user: root
  #    password: admin123
  #    locations: classpath:db/migration

  #Jackson Configuration (enforce strict deserialization)
  jackson:
    deserialization:
      fail-on-unknown-properties: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      probes:
        enabled: true

app:
  security:
    allowed-email-domain: seek.com
    jwt:
      secret: "n8YxPq2mV7sL1cK9dR4eT6uW0zA3bH5jQ8sF2gJ7kL9mN1pR4tV6xZ0cD3eG5hJ"
      issuer: "clients-service"
      ttl-minutes: 60

  life:
    expectancy-years: 73

  sql:
    init:
      mode: never

  openapi:
    title: Applicant Management System API
    description: API para gesti√≥n de clientes
    version: v1
    terms-of-service: https://example.com/terms
    contact:
      name: DevPull
      url: https://www.devpull.dev
      email: hello@devpull.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
    ui:
      enabled: true
      path: /swagger

  springdoc:
    swagger-ui:
      path: ${app.openapi.ui.path:/swagger}
    api-docs:
      path: /v3/api-docs
